version: 2.1

executors:
  builder:
    environment:
      IMAGE_NAME: nibbleproject/nibble
    docker:
      - image: nibbleproject/nibble-ci

jobs:
  test:
    executor: builder
    steps:
      - checkout
      - run:
          name: Install requirements
          command: sudo pipenv install --system --dev
      - run:
          name: Run tests
          command: CI=true make test
      - run:
          name: Report Coverage
          command:
            coveralls
  build_image:
    executor: builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Archive image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  push_image:
    executor: builder
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Push image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  image_test:
    executor: builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install requirements
          command: sudo pipenv install --system --dev
      - run:
          name: Smoke test
          command: |
            set -x
            docker-compose up -d
            docker run -it --network project_default nibbleproject/nibble-ci curl --retry 10 --retry-delay 1 --retry-connrefused web:5000
  deploy_staging:
    executor: builder
    steps:
      - checkout
      - run:
          name: Configure Heroku
          command: |
            cat > ~/.netrc \<< EOF
            machine api.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_AUTH_TOKEN
            EOF
      - add_ssh_keys:
          fingerprints:
            - "61:66:4f:6c:6a:a6:1b:c3:18:18:04:2a:32:d0:b3:79"
      - run:
          name: Deploy to staging
          command: |
            heroku git:remote --app nibbleproject-staging --ssh-git
            git push heroku master
  deploy_production:
    executor: builder
    steps:
      - checkout
      - run:
          name: Configure Heroku
          command: |
            cat > ~/.netrc \<< EOF
            machine api.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_AUTH_TOKEN
            EOF
      - add_ssh_keys:
          fingerprints:
            - "61:66:4f:6c:6a:a6:1b:c3:18:18:04:2a:32:d0:b3:79"
      - run:
          name: Deploy to production
          command: |
            heroku git:remote --app nibbleproject-staging --ssh-git
            heroku pipelines:promote

workflows:
  version: 2
  main:
    jobs:
      - test
      - build_image
      - image_test
      - push_image:
          requires:
            - build_image
            - image_test
          filters:
            branches:
              only: ci-docker
      - deploy_staging:
          requires:
            - test
            - push_image
          filters:
            branches:
              only: main
      - hold:
          type: approval
          requires:
            - deploy_staging
          filters:
            branches:
              only: main
      - deploy_production:
          requires:
            - hold
          filters:
            branches:
              only: main
