version: 2
jobs:
  test:
    docker:
      - image: nibbleproject/nibble-ci
    steps:
      - checkout
      - run:
          name: Install requirements
          command: sudo pipenv install --system --dev
      - run:
          name: Run tests
          command: CI=true make test
      - run:
          name: Report Coverage
          command:
            coveralls
  build_image:
    docker:
      - image: nibbleproject/nibble-ci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t nibbleproject/nibble:latest .
  image_test:
    docker:
      - image: nibbleproject/nibble-ci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install requirements
          command: sudo pipenv install --system --dev
      - run:
          name: Smoke test
          command: |
            set -x
            docker-compose up -d
            docker run -it --network project_default nibbleproject/nibble-ci curl --retry 10 --retry-delay 1 --retry-connrefused web:5000
  deploy_staging:
    docker:
      - image: nibbleproject/nibble-ci
    steps:
      - checkout
      - run:
          name: Configure Heroku
          command: |
            cat > ~/.netrc << EOF
            machine api.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_AUTH_TOKEN
            EOF
      - add_ssh_keys:
          fingerprints:
            - "61:66:4f:6c:6a:a6:1b:c3:18:18:04:2a:32:d0:b3:79"
      - run:
          name: Deploy to staging
          command: |
            heroku git:remote --app nibbleproject-staging --ssh-git
            git push heroku master
  deploy_production:
    docker:
      - image: nibbleproject/nibble-ci
    steps:
      - checkout
      - run:
          name: Configure Heroku
          command: |
            cat > ~/.netrc << EOF
            machine api.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_AUTH_TOKEN
            EOF
      - add_ssh_keys:
          fingerprints:
            - "61:66:4f:6c:6a:a6:1b:c3:18:18:04:2a:32:d0:b3:79"
      - run:
          name: Deploy to production
          command: |
            heroku git:remote --app nibbleproject-staging --ssh-git
            heroku pipelines:promote

workflows:
  version: 2
  main:
    jobs:
      - test
      - build_image
      - image_test
      - deploy_staging:
          requires:
            - test
            - image_test
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - deploy_staging
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - hold
          filters:
            branches:
              only: master
