web:
  build: .
  environment:
    - DATABASE_USER
    - DATABASE_PASSWORD
  links:
    - postgres
  ports:
    - "5000:5000"
postgres:
  image: postgres
  environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=test
